# Generated by Django 4.2.7 on 2023-12-24 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('New', 'N'), ('Repaired in Shop', 'D'), ('Merchandise Returns', 'R'), ('Clearance Item', 'C')], max_length=20)),
                ('status', models.CharField(choices=[('Repair In Progress', 'Repair In Progress'), ('Repair Complete', 'Repair Complete')], default='Repair In Progress', max_length=25)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
