# Generated by Django 4.2.7 on 2023-12-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointpiece',
            name='lp',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='pointpiece',
            name='route',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='pointpiece',
            name='sku',
            field=models.PositiveSmallIntegerField(blank=True, default=123),
            preserve_default=False,
        ),
    ]
