# Generated by Django 4.2.7 on 2024-01-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0003_alter_pointpiece_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointpiece',
            name='line_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pointpiece',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
