# Generated by Django 4.2.7 on 2024-01-13 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pointqueapp', '0004_pointpiece_line_time_alter_pointpiece_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointpiece',
            name='associate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
