# Generated by Django 4.2.7 on 2024-01-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0007_repairtype_pointpiece_repair'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='pointpiece',
            name='part',
            field=models.ManyToManyField(to='pointqueapp.parttype'),
        ),
    ]
