# Generated by Django 4.2.7 on 2024-01-16 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0010_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointpiece',
            name='associate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointqueapp.associate'),
        ),
    ]
