# Generated by Django 4.2.7 on 2024-01-16 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0011_alter_pointpiece_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointpiece',
            name='associate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pointqueapp.associate'),
        ),
    ]
