# Generated by Django 4.2.7 on 2024-01-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0012_alter_pointpiece_associate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate',
            name='associate',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
