# Generated by Django 4.2.7 on 2024-01-18 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointqueapp', '0013_alter_associate_associate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=3)),
            ],
        ),
    ]
